name: delete-deployment-history

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering

permissions:
  contents: write
  deployments: write

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
